src/agri/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from apps.usuarios.views import RegistroUsuario
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.contrib.auth.views import logout

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include ('apps.base.urls'), name='base'),
    url(r'^principal/', include ('apps.sistema.urls'), name='base'),
    url(r'^registrarse$', RegistroUsuario.as_view(), name='registrarse'),
    url(r'^login/', auth_views.LoginView.as_view(template_name='agri/login.html'), name='login'),
    url(r'^logout/', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    path('accounts/', include('allauth.urls')),
    
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/apps/base/urls.py
from django.conf.urls import url, include
from apps.base.views import index, informacion

from django.urls import include, path

app_name = "base";

urlpatterns = [
url(r'^$', index,name='index'),
url(r'^info$',informacion,name='informacion')
]

src/apps/sistema/urls.py
from django.conf.urls import url, include
from apps.sistema.views import index,registrarproductos,listar_productos,listar_productos2,registrartarjetas

from django.urls import include, path

app_name = "sistema";

urlpatterns = [
    url(r'^$', index,name='index'),
    url(r'^nuevoproducto', registrarproductos,name='newprod'),
    url(r'^listarproductos', listar_productos,name='listaprod'),
    url(r'^lista_produc2(?P<id_producto>\d+)/$', listar_productos2, name='listaproducto2'),
    url(r'^tarjetas', registrartarjetas,name='newtarjet'),
]

src/apps/sistema/models.py
from django.db import models
from apps.usuarios.models import User

# Create your models here.


class registro(models.Model):

	Tipo = (('palta','palta'),('damasco','damasco'),('piña','piña'),('arándano','arándano'),('arándano (rojo)','arándano (rojo)'),
		('plátano','plátano'),('guinda','guinda'),('ciruela','ciruela'),('coco','coco'),('frambuesa','frambuesa'),('frutilla','frutilla'),
		('fresa','fresa'),('cereza','cereza'),('granada','granada'),('higo','higo'),('kiwi','kiwi'),('lima','lima'),('limón','limón'),
		('mandarina','mandarina'),('mango','mango'),('manzana','manzana'),('maracuyá','maracuyá'),('durazno','durazno'),('melón','melón'),
		('membrillo','membrillo'),('mora','mora'),('naranja','naranja'),('nectarina','nectarina'),('papaya','papaya'),('pera','pera'),
		('pomelo','pomelo'),('sandía','sandía'),('uva','uva'),(' zarzamora',' zarzamora'),
		('acelga','acelga'),('ajo','ajo'),('alcachofa','alcachofa'),('alcaucil','alcaucil'),('apio','apio'),('arveja','arveja'),
		('batata','batata'),('berenjena','berenjena'),('betarraga','betarraga'),('brócoli','brócoli'),('zapallo','zapallo'),('camote','camote'),
		('cebolla','cebolla'),('champiñón','champiñón'),('choclo','choclo'),('repollo','repollo'),('coles de Bruselas','coles de Bruselas'),
		('zapallo italiano','zapallo italiano'),('coliflor','coliflor'),('maíz','maíz'),('espárrago','espárrago'),('espinaca','espinaca'),
		('frijol','frijol'),('guisante','guisante'),('jitomate','jitomate'),('poroto','poroto'),('lechuga','lechuga'),
		('repollo morado','repollo morado'),('papa','papa'),('pepino','pepino'),('pimentón','pimentón'),('pimiento','pimiento'),('puerro','puerro'),
		('rábano','rábano'),('remolacha','remolacha'),('seta','seta'),('tomate','tomate'),('zanahoria','zanahoria'))
	TipoFruVer = models.CharField(max_length=50,choices=Tipo,default='papa')
	FotoProducto = models.FileField(upload_to="projects")	
	NombreProducto = models.CharField(max_length = 50)
	CantidadKG = models.IntegerField()
	Precio = models.IntegerField()
	UsuarioName = models.CharField(max_length = 50)
	Usuario = models.ForeignKey(User,on_delete=models.CASCADE)
	Latitud = models.CharField(max_length=200)
	Longitud = models.CharField(max_length=200)


class compra(models.Model):
	idproducto = models.IntegerField()
	cantidad = models.IntegerField()
	valor = models.IntegerField()
	vendedor = models.CharField(max_length=200)
	comprador = models.CharField(max_length=200)
	tipopago = models.CharField(max_length=200)


class tarjetas(models.Model):
	idusuario = models.IntegerField()
	Tipos = (('Santander','Banco Santander'),('Banco BBVA','Banco BBVA'),('Banco de Chile','Banco de Chile'),('BancoEstado','BancoEstado'),('Banco Scotiabank','Banco Scotiabank'),
		('Banco Itau','Banco Itau'),('Banco Falabella','Banco Falabella'),('Visa','Visa'),('Mastercard','Mastercard'))
	tipotarjeta = models.CharField(max_length=50,choices=Tipos,default='Santander')
	numero = models.CharField(max_length = 16)
	Meses = (('1','1'),('2','2'),('3','3'),('4','4'),('5','5'),('6','6'),('7','7'),('8','8'),('9','9'),('10','10'),('11','11'),('12','12'))
	mesvencimiento = models.CharField(max_length = 99,choices=Meses,default='1')
	Años = (('2018','2018'),('2019','2019'),('2020','2020'),('2021','2021'),('2022','2022'),('2023','2023'),('2024','2024'),('2025','2025'))
	añovencimiento = models.CharField(max_length = 9999,choices=Años,default='2018')
	cvc = models.CharField(max_length = 3)

src/templates/agri/index.html
{% extends 'base/base.html' %}

src/templates/agri/listar_productos.html
{% extends 'base/base_logeado.html' %}

{% block content %}

<div align="center">
	<h1 style="font-family: times;" > PRODUCTOS PUBLICADOS </h1>
</div>
<br>

{% load staticfiles %}

		{% if productos %}
		{% for producto in productos %}
		<div>
			<center>
				<img style="width:200px;height: 200px;"  src="{{ producto.FotoProducto.url }}">
				<center>{{ producto.TipoFruVer }}</center>
				<center> Cantidad: {{ producto.CantidadKG }} KG</center>
				<center> Precio: ${{ producto.Precio }}</center>
				<center> Vendedor: {{ producto.UsuarioName }}</center>
				<center> <a href="{% url 'sistema:listaproducto2' producto.id %}">Ver ubicación</a></center>
			</center>
		</div>
		{% endfor %}
		{% else %}
		<h1>No hay productos</h1>
		{% endif %}

{% endblock %}

src/templates/agri/listar_productos2.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">

    {% block extrastatic %}

    {% endblock %}

    <meta name="viewport" content="initial-scale=1.0, width=device-width" />
    <link rel="stylesheet" type="text/css" href="https://js.api.here.com/v3/3.0/mapsjs-ui.css?dp-version=1549984893" />
    <script type="text/javascript" src="https://js.api.here.com/v3/3.0/mapsjs-core.js"></script>
    <script type="text/javascript" src="https://js.api.here.com/v3/3.0/mapsjs-service.js"></script>
    <script type="text/javascript" src="https://js.api.here.com/v3/3.0/mapsjs-ui.js"></script>
    <script type="text/javascript" src="https://js.api.here.com/v3/3.0/mapsjs-mapevents.js"></script>

    
	  <link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/estilos-logeado.css' %}">
    {% block title %}
    <title>Menu principal</title>
    {% endblock%}

</head>

<body class="bodyuser">

<header>
	<input type="checkbox" id="btn-menu">
	<label for="btn-menu"><img src="/static/img/menu.png" alt="" class="imagen-menu"></label>

	<nav class="menu">
		<ul>
			<ul><li><a href="{% url 'sistema:index' %}">Inicio</a></li></ul>
			<ul><li><a href="{% url 'sistema:newprod' %}"> Registrar Producto</a></li></ul>
      <ul><li><a href="{% url 'sistema:listaprod' %}"> Comprar productos</a></li></ul>
      <ul><li><a href="{% url 'logout' %}"> Cerrar Sesion </a></li></ul>
		</ul>
	</nav>
</header>


<br>
<br>
<center>
  <div id="map" style="width: 500px; height: 500px; background: grey;" />
</center>
<p id="latitud" value="{{ productos2.Latitud }}"></p>
<p id="longitud" value="{{ productos2.Longitud }}"></p>

<script  type="text/javascript" charset="UTF-8" >

function moveMapToBerlin(map){
  map.setCenter({lat:-33.447487, lng:-70.673676});
  map.setZoom(11);
}

var platform = new H.service.Platform({
  app_id: 'm2B0eh8gClt3nAHe9nRz',
  app_code: 'cCUbdNpqqcmgUzUuDVvHkQ',
  useHTTPS: true
});

var pixelRatio = window.devicePixelRatio || 1;

var defaultLayers = platform.createDefaultLayers({
  tileSize: pixelRatio === 1 ? 256 : 512,
  ppi: pixelRatio === 1 ? undefined : 320
});

var map = new H.Map(document.getElementById('map'),
  defaultLayers.normal.map, {pixelRatio: pixelRatio});

var behavior = new H.mapevents.Behavior(new H.mapevents.MapEvents(map));

var ui = H.ui.UI.createDefault(map, defaultLayers);

moveMapToBerlin(map);
var latt = {{ productos2.Latitud }};
var longg = {{ productos2.Longitud }};

var icon = new H.map.Icon("https://image.flaticon.com/icons/svg/1041/1041355.svg", {size: {w: 32, h: 32}}),
  coords = {lat: latt, lng: longg},
  marker = new H.map.Marker(coords, {icon: icon});

map.addObject(marker);
map.setCenter(coords);



function Sumar() {
            var n1 = document.getElementById('id_precio').value;
            var n2 = document.getElementById('id_cantidad').value;
            var suma = parseInt(n1) * parseInt(n2);
            if(n2 > {{ productos2.CantidadKG }}){
              alert("La cantidad supera a la publicada")
              document.getElementById('id_valor').value = "";
            }
            else
            {
              if(n2 == 0 || n2 == ""){
                alert("Ingrese una cantidad")
                document.getElementById('id_valor').value = "";
              }
              else
              {
                document.getElementById('id_valor').value = suma;
              }
            } 
        }

</script>

<div>
    <form method="POST" enctype="multipart/form-data" class="formulario">

    {% csrf_token %}

    <h2>Cantidad Publicada: {{ productos2.CantidadKG }} Kg.</h2>
    <h2>Precio Unidad: ${{ productos2.Precio }}</h2>
    <h2>Cantidad a comprar (Kg)</h2>
    <input type="text" name="cantidad" required="" id="id_cantidad">
    <input type="button" onclick="Sumar();" value="Calcular">
    <h2>Total a pagar:</h2>
    <input type="text" name="valor" required="" id="id_valor" readonly="true">
    <h2>Vendedor: {{ productos2.UsuarioName }}</h2>




    <div style="display: none;">
        <input type="text" name="precio" class="form-control col-10" required="" id="id_precio" value="{{ productos2.Precio }}">
        <input type="text" name="idproducto" class="form-control col-10" required="" id="id_idproducto" value="{{ productos2.id }}">
        <input type="text" name="vendedor" class="form-control col-10" maxlength="200" required="" id="id_vendedor" value="{{ productos2.UsuarioName }}">
        <input type="text" name="comprador" class="form-control col-10" maxlength="200" required="" id="id_comprador" value="{{ request.user }}">
    </div>

<br>
<button type="submit" class="btn btn-primary btn-block btn-success"> REGISTRAR NUEVA ORDEN</button>
</form>
</div>

<span id="Display"></span>


<div class="finalizar">

            <p>Duoc 2019</p>
    <br>
    <br>
    <br>

</div>


<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="https://js.api.here.com/v3/3.0/mapsjs-pano.js"></script>

</body>
</html>

src/templates/agri/login.html
{% load staticfiles %}
{% load static %}
{% load socialaccount %}
{% providers_media_js %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    
	<link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
    <meta name="viewport" content="width=device-width">
    <title>Login</title>

</head>

<body class="bodyuser">

<header>
	<input type="checkbox" id="btn-menu">
	<label for="btn-menu"><img src="/static/img/menu.png" alt="" class="imagen-menu"></label>

	<nav class="menu">
		<ul>
			<ul ><li><a href="{% url 'base:index' %}">Inicio</a></li></ul>
			<ul> <li> <a href="{% url 'registrarse' %}"> Registrate </a> </li> </ul>
			<ul><li><a href="{% url 'login' %}">iniciar sesion</a></li></ul>
		</ul>
	</nav>
</header>



{% block content %}

<div class="divlogin">

<center>
	<h1>INICIAR SESION</h1>
</center>

<center>

<form method="post">
{% csrf_token %}

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<div class="form-group" style="margin-top: 10px;">

			<label for="username">NOMBRE DE USUARIO O CORREO ELECTRONICO</label>
			<input class="form-control" type="text" name="username">
				
		</div>
	</div>
</div>

<div class="row" id="contra">
	<div class="col-md-6 col-md-offset-3">
		<div class="form-group">

			<label for="password">CONTRASEÑA</label>
			<input class="form-control" type="password" name="password">
				
		</div>
	</div>
</div>

<div class="row" id="botones">
	<div class="col-md-6 col-md-offset-3">
		<div class="form-group">

			<a href="{% url 'registrarse' %}" class="btn btn-primary" id="botonreg">Registrarse</a>
			<input class="btn btn-primary" type="submit" value="Ingresar" id="botonlog">
				
		</div>
	</div>
</div>

<div class="row" id="botones">
	<div class="col-md-6 col-md-offset-3">
		<div class="form-group">

			<a href="{% provider_login_url "facebook" method="js_sdk" %}" class="btn btn-primary" id="botonface">Facebook</a>
			
		</div>
	</div>
</div>

</form>
</center>

</div>

{% endblock %}

<a href="#"></a>

{% block footer %}

<div class="finalizar">

            <p>Duoc 2019</p>
    <br>
    <br>
    <br>

</div>

{% endblock %}

<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>

src/templates/agri/menu-principal.html
{% extends 'base/base_logeado.html' %}

{% block content %}
    <br>
    <br>
    <center>
        <img src="/static/img/1.png" style="width: 600px;height: 400px; max-width: 100%;">
    </center>
{% endblock %}

src/templates/agri/registrar.html
{% extends 'base/base.html' %}

{% block content %}

<form method="post">

{% csrf_token %}

	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group" style="margin-top: 20px;">

				<label style="font-size: 20px;">Nombre</label>
				<input class="form-control" type="text" name="first_name">

				{% for error in form.first_name.errors %}
				<div class="alert alert-danger">
	                <strong> Debe ingresar al menos un nombre </strong>
	            </div>
	            {% endfor %}
					
			</div>
		</div>
	</div>


	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">

				<label style="font-size: 20px;">Apellido</label>
				<input class="form-control" type="text" name="last_name">

				{% for error in form.last_name.errors %}
				<div class="alert alert-danger">
	                <strong> Debe ingresar al menos un apellido </strong>
	            </div>
	            {% endfor %}
					
			</div>
		</div>
	</div>


	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">

				<label style="font-size: 20px;">Nombre de usuario</label>
				<input class="form-control" type="text" name="username">

				{% for error in form.username.errors %}
				<div class="alert alert-danger">
	                <strong> Debe ingresar un nombre de usuario </strong>
	            </div>
	            {% endfor %}
					
			</div>
		</div>
	</div>


	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">

				<label style="font-size: 20px;">Correo</label>
				<input class="form-control" type="text" name="email">

				{% for error in form.email.errors %}
				<div class="alert alert-danger">
	                <strong> Debe ingresar un correo valido </strong>
	            </div>
	            {% endfor %}
					
			</div>
		</div>
	</div>


	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">

				<label style="font-size: 20px;">Contraseña</label>
				<input class="form-control" type="password" name="password1">
					
			</div>
		</div>
	</div>


	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">

				<label style="font-size: 20px;">Repita la Contraseña</label>
				<input class="form-control" type="password" name="password2">

				{% for error in form.first_name.errors %}
				<div class="alert alert-danger">
	                <strong> Las contraseñas no coinciden </strong>
	            </div>
	            {% endfor %}
					
			</div>
		</div>
	</div>

<center>
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">

				<button class="btn btn-primary" type="submit" style="font-size: 20px;" id="boton">Registrar</button>
				<a class="btn btn-primary" href="{% url 'base:index' %}" style="font-size: 20px;" id="boton">volver</a>
					
			</div>
		</div>
	</div>	
</center>

</form>

{% endblock %}

src/templates/agri/registro-productos.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">

    {% block extrastatic %}

    {% endblock %}

    <link rel="stylesheet" href="{% static 'css/fontello.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> 
    <link rel="stylesheet" href="{% static 'css/estilos-logeado.css' %}">
    <meta name="viewport" content="width=device-width">

    {% block title %}
    <title>Menu principal</title>
    {% endblock%}

    <script>

    function funcion(){
      var options = {
        enableHighAccuracy: true,
        timeout: 5000,
        maximumAge: 0
      };

    function success(pos) {
      var crd = pos.coords;

      console.log('Your current position is:');
      console.log('Latitude : ' + crd.latitude);
      console.log('Longitude: ' + crd.longitude);
      console.log('More or less ' + crd.accuracy + ' meters.');
      document.getElementById("id_Latitud").value = crd.latitude;
      document.getElementById("id_Longitud").value = crd.longitude;
    };

    function error(err) {
      console.warn('ERROR(' + err.code + '): ' + err.message);
    };

    navigator.geolocation.getCurrentPosition(success, error, options);
        }


    </script>
</head>

<body class="bodyuser" onload="funcion();">

<header>
  <input type="checkbox" id="btn-menu">
  <label for="btn-menu"><img src="/static/img/menu.png" alt="" class="imagen-menu"></label>

  <nav class="menu">
    <ul>
      <ul><li><a href="{% url 'sistema:index' %}">Inicio</a></li></ul>
      <ul><li><a href="{% url 'sistema:newprod' %}"> Registrar Producto</a></li></ul>
      <ul><li><a href="{% url 'sistema:listaprod' %}"> Comprar productos</a></li></ul>
      <ul><li><a href="{% url 'logout' %}"> Cerrar Sesion </a></li></ul>
    </ul>
  </nav>
</header>

<div id="div-formulario">

  <form method="POST"  enctype="multipart/form-data" class="formulario">

    {% csrf_token %}
    <h2>TIPO DE FRUTA/VERDURA</h2>
    {{ form.TipoFruVer }}
    <h2>FOTO DEL PRODUCTO</h2>
    {{ form.FotoProducto }}
    <h2>DESCRIPCION</h2>
    {{ form.NombreProducto }}
    <h2>CANTIDAD (KG)</h2>
    {{ form.CantidadKG }}
    <h2>PRECIO</h2>
    {{ form.Precio }}
    <div style="display: none;">
    <h2>Usuario</h2>
    <input type="text" name="UsuarioName" class="form-control col-10" maxlength="50" required id="id_UsuarioName" value="{{ request.user }}">
    <h2>Usuario id</h2>
    <input type="text" name="Usuario" class="form-control" required id="id_Usuario" value="{{ request.user.id }}">
    <h2>Latitud</h2>
    {{ form.Latitud }}
    <h2>Longitud</h2>
    {{ form.Longitud }}
  </div>
  

<br>
<button type="submit" class="btn btn-primary btn-block btn-success"> REGISTRAR NUEVA ORDEN</button>
</form>
  
</div>





{% block footer %}

<div class="finalizar">

            <p>Duoc 2019s</p>
    <br>
    <br>
    <br>

</div>

{% endblock %}

<script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>


</body>
</html>